site_name: OpenTimeWatch Docs
site_url: https://sitename.example
repo_name: OpenTimeWatch-Project/OpenTimeWatch-OS
repo_url: https://github.com/OpenTimeWatch-Project/OpenTimeWatch-OS
theme:
  name: material
  font:
    code: Red Hat Mono
  logo: assets/Logo.png
  icon:
    repo: fontawesome/brands/git-alt
  features: 
    - navigation.footer
    - header.autohide
  palette:
    # Dark Mode
    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Dark mode
      primary: lime
      accent: deep purple

    # Light Mode
    - scheme: default
      toggle:
        icon: material/weather-night
        name: Light mode
      primary: lime
      accent: deep purple
markdown_extensions:
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - admonition
  - pymdownx.details
  - md_in_html
  - pymdownx.blocks.caption
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
extra:
  social:
    - icon: fontawesome/brands/github 
      link: https://github.com/OpenTimeWatch-Project
copyright: Copyright &copy; 2024 - 2025 OpenTimeWatch Project. Made in India